version: '1.0'
name: branch-pipeline
displayName: BranchPipeline
stages:
  - stage: 
    name: compile
    displayName: 编译
    steps:
      - step: build@golang
        name: build_golang
        displayName: Golang 构建
        # Go版本1.24
        golangVersion: '1.24'
        # 构建命令
        commands: |
          #!/bin/bash
          set -e

          echo "===== 配置Go环境 ====="
          # 强制使用国内镜像
          export GOPROXY=https://goproxy.cn,https://goproxy.io
          export GOSUMDB=sum.golang.google.cn
          export GO111MODULE=on
          export GONOPROXY=""
          export GONOSUMDB=""
          export GOPRIVATE=""

          echo "Go version:"
          go version

          # 创建输出目录
          mkdir -p output

          echo "===== 开始构建 ====="
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -mod=readonly -ldflags "-w -s" -trimpath -o output/yun-linux-amd64 main.go
          CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -mod=readonly -ldflags "-w -s" -trimpath -o output/yun-linux-arm64 main.go
          CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -mod=readonly -ldflags "-w -s" -trimpath -o output/yun-windows-amd64.exe main.go
          CGO_ENABLED=0 GOOS=windows GOARCH=386 go build -mod=readonly -ldflags "-w -s" -trimpath -o output/yun-windows-386.exe main.go

          echo "===== 构建完成 ====="
          ls -lh output/
        # 非必填字段，开启后表示将构建产物暂存，但不会上传到制品库中，7天后自动清除
        artifacts:
            # 构建产物名字，作为产物的唯一标识可向下传递，支持自定义，默认为BUILD_ARTIFACT。在下游可以通过${BUILD_ARTIFACT}方式引用来获取构建物地址
          - name: BUILD_ARTIFACT
            # 构建产物获取路径，是指代码编译完毕之后构建物的所在路径
            path:
              - ./output
      - step: publish@general_artifacts
        name: publish_general_artifacts
        displayName: 上传制品
        # 上游构建任务定义的产物名，默认BUILD_ARTIFACT
        dependArtifact: BUILD_ARTIFACT
        # 上传到制品库时的制品命名，默认output
        artifactName: output
        dependsOn: build_golang
  - stage: 
    name: release
    displayName: 发布
    steps:
      - step: publish@release_artifacts
        name: publish_release_artifacts
        displayName: '发布'
        # 上游上传制品任务的产出
        dependArtifact: output
        # 发布制品版本号
        version: '1.0.0.0'
        # 是否开启版本号自增，默认开启
        autoIncrement: true
triggers:
  push:
    branches:
      exclude:
        - master
      include:
        - .*
