version: '1.0'
name: main-pipeline
displayName: Main分支流水线

# 触发条件：推送到main分支时执行
triggers:
  push:
    branches:
      include:
        - main

stages:
  - stage:
      name: build_test
      displayName: 构建测试
      steps:
        - step: build@golang
          name: build_main
          displayName: Go构建测试
          golangVersion: '1.16'
          commands: |
            echo "===== 开始构建测试 ====="
            go version
            go build -o yun-test main.go
            echo "✓ 构建成功"

            # 显示版本号
            VERSION=$(cat config/version)
            echo "当前版本: $VERSION"
            echo "===== 构建测试完成 ====="

