version: '1.0'
name: main-pipeline
displayName: Main分支流水线

# 触发条件：推送到main分支时执行
triggers:
  push:
    branches:
      include:
        - main

stages:
  - stage:
      name: build_test
      displayName: 构建测试
      steps:
        - step: build@golang
          name: build_main
          displayName: Go构建测试
          golangVersion: '1.21'
          commands: |
            #!/bin/bash
            set -e

            echo "===== 配置Go环境 ====="
            export GOPROXY=https://goproxy.cn,https://goproxy.io,direct
            export GOSUMDB=sum.golang.google.cn
            export GO111MODULE=on
            export GOTOOLCHAIN=local

            echo "===== 开始构建测试 ====="
            go version
            echo "GOPROXY: $GOPROXY"

            # 预下载依赖
            go mod download || { echo "依赖下载失败，尝试清理缓存"; go clean -modcache; go mod download; }

            # 构建测试
            CGO_ENABLED=0 go build -ldflags "-w -s" -trimpath -o yun-test main.go
            echo "✓ 构建成功"

            # 显示版本号
            VERSION=$(cat config/version | tr -d '\n\r')
            echo "当前版本: $VERSION"
            echo "===== 构建测试完成 ====="

